variable "public_domain" {
  description = "The public domain generated by Railway (e.g. exemplary-solace-production-1bf7.up.railway.app)"
  type        = string
}

variable "app_secret" {
  description = "The application secret for JWT validation"
  type        = string
  sensitive   = true
}

variable "github_pat" {
  description = "GitHub Personal Access Token for GHCR"
  type        = string
  sensitive   = true
}
